before_install: sudo apt-get install libzmq3-dev
script: bundle exec rspec
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 3.3.5
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
